services:
  go-chatgpt-api:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    container_name: go-chatgpt-api
    image: go-chatgpt-api
    ports:
      - 18999:8080
    environment:
      - PORT=8080
      - TZ=Asia/Shanghai
      - PROXY=http://192.168.33.51:7890
      - OPENAI_EMAIL=
      - OPENAI_PASSWORD=
      - CONTINUE_SIGNAL=
      - ENABLE_HISTORY=
      - IMITATE_ACCESS_TOKEN=
    volumes:
      - ./chat.openai.com.har:/app/chat.openai.com.har
    restart: unless-stopped
